# Generated by Django 6.0.4 on 2026-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ID техники')),
                ('week_start', models.DateField(db_index=True, verbose_name='Начало недели')),
                ('week_end', models.DateField(verbose_name='Конец недели')),
                ('weekly_limit', models.FloatField(default=0.0, verbose_name='Недельный лимит')),
                ('new_month_limit', models.FloatField(blank=True, null=True, verbose_name='Новый месячный лимит')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Недельный лимит',
                'verbose_name_plural': 'Недельные лимиты',
                'db_table': 'week_limits',
                'unique_together': {('user_id', 'week_start')},
            },
        ),
    ]
