# Generated by Django 6.0.4 on 2026-07-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, verbose_name='ID техники')),
                ('date_from', models.DateField(db_index=True, verbose_name='Начало периода')),
                ('date_to', models.DateField(verbose_name='Конец периода')),
                ('period_limit', models.FloatField(default=0.0, verbose_name='Лимит на период')),
                ('new_month_limit', models.FloatField(blank=True, null=True, verbose_name='Накопленный месячный лимит')),
                ('remaining_at_period_end', models.FloatField(blank=True, null=True, verbose_name='Остаток на конец периода')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Лимит на период',
                'verbose_name_plural': 'Лимиты на периоды',
                'db_table': 'period_limits',
                'unique_together': {('user_id', 'date_from', 'date_to')},
            },
        ),
    ]
