# Generated by Django 6.0.4 on 2026-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklimit',
            name='week_remaining',
            field=models.FloatField(blank=True, null=True, verbose_name='Остаток на конец недели'),
        ),
        migrations.AlterField(
            model_name='weeklimit',
            name='new_month_limit',
            field=models.FloatField(blank=True, null=True, verbose_name='Новый месячный лимит (накопленный)'),
        ),
    ]
